#!/usr/bin/env python3
"""Generate global (~/.claude/skills) redirect stubs for this repo's skills.

The canonical skills live in <repo>/.claude/skills/ and are only discoverable
when Claude Code runs inside this repo. This script mirrors upstream's own
`sync_codex_stubs.py` pattern, but writes stubs into the user-level skills
directory with ABSOLUTE paths so the skills work from any working directory.

Never hand-edit the generated stubs. Edit the canonical tree, then re-run:

    python3 tools-local/sync_global_stubs.py

Re-run after every `git pull`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CANONICAL_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
DEFAULT_GLOBAL_DIR = Path.home() / ".claude" / "skills"
MARKER = "<!-- slide-master-global-stub -->"
ADDENDUM = "<!-- wdb-confirm-ui -->"


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block_including_fences, body)."""
    if not text.startswith("---"):
        raise ValueError("SKILL.md does not start with YAML frontmatter")
    lines = text.splitlines(keepends=True)
    for i in range(1, len(lines)):
        if lines[i].rstrip("\n") == "---":
            return "".join(lines[: i + 1]), "".join(lines[i + 1 :])
    raise ValueError("unterminated YAML frontmatter")


def build_stub(name: str, frontmatter: str) -> str:
    skill_dir = CANONICAL_SKILLS_DIR / name
    return f"""{frontmatter}
{MARKER}
# {name} — global redirect stub

Generated by `tools-local/sync_global_stubs.py`. Do not hand-edit.
The authoritative skill lives at:

    {skill_dir}

## On invocation

1. Read `{skill_dir}/SKILL.md` **in full** and execute it exactly as a runtime
   procedure. Do not summarise or skim it. Any arguments passed to this stub
   apply verbatim to the canonical skill.

2. Resolve every path in the canonical text as follows:

   - `${{SKILL_DIR}}` = `{skill_dir}`
   - Bare relative paths (`references/...`, `workflows/...`, `scripts/...`,
     `templates/...`, `assets/...`) resolve against `${{SKILL_DIR}}`.
   - A literal `.claude/skills/<other>/...` written in the canonical text is
     repo-relative and MUST be read as
     `{CANONICAL_SKILLS_DIR}/<other>/...`.
     (e.g. `.claude/skills/ppt-master/scripts/project_manager.py`
     -> `{CANONICAL_SKILLS_DIR}/ppt-master/scripts/project_manager.py`)
   - Instructions to read a sibling skill (`diagram-design`, `ppt-master`, ...)
     resolve to that skill's canonical directory above.

3. Execution environment:

   - Invoke scripts with `python3` (fall back to `python` if absent), always by
     ABSOLUTE path. Do not `cd` into the repo — the scripts locate their own
     resources from `__file__`.

4. Deck output location:

   - Create deck projects under **the user's current working directory**, i.e.
     `<cwd>/projects/<project_name>` — this is `project_manager.py init`'s
     default behaviour (`Path.cwd() / "projects"`), so pass no `--dir` unless
     the user names an explicit location.
   - Honour an explicit `--dir` / user-specified path when given.
   - Never write deck output into `{REPO_ROOT}` — that path holds the skill
     itself, not the user's decks.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--global-dir",
        type=Path,
        default=DEFAULT_GLOBAL_DIR,
        help=f"target skills directory (default: {DEFAULT_GLOBAL_DIR})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift without writing",
    )
    args = parser.parse_args()

    if not CANONICAL_SKILLS_DIR.is_dir():
        print(f"canonical skills dir not found: {CANONICAL_SKILLS_DIR}", file=sys.stderr)
        return 1

    args.global_dir.mkdir(parents=True, exist_ok=True)
    stale = 0

    for skill_md in sorted(CANONICAL_SKILLS_DIR.glob("*/SKILL.md")):
        name = skill_md.parent.name
        # Mirror only upstream's own skills. Third-party skills installed into
        # this repo's .claude/skills/ arrive as symlinks (e.g. the HeroUI set);
        # they are already globally usable and must not be wrapped in a stub.
        if skill_md.parent.is_symlink():
            print(f"skip  {name}: symlinked third-party skill")
            continue
        frontmatter, _ = split_frontmatter(skill_md.read_text(encoding="utf-8"))
        want = build_stub(name, frontmatter)

        target_dir = args.global_dir / name
        target = target_dir / "SKILL.md"

        addendum = ""
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if MARKER not in existing:
                print(f"SKIP  {name}: {target} exists and is not our stub", file=sys.stderr)
                stale += 1
                continue
            # Preserve a hand-wired local addendum (e.g. the WDB confirm-UI override)
            # so regenerating the stub never silently reverts it.
            if ADDENDUM in existing:
                addendum = "\n" + ADDENDUM + existing.split(ADDENDUM, 1)[1].rstrip() + "\n"
                want = want.rstrip() + "\n" + addendum
            if existing == want:
                print(f"ok    {name}")
                continue
        elif target_dir.exists() and not target_dir.is_dir():
            print(f"SKIP  {name}: {target_dir} is not a directory", file=sys.stderr)
            stale += 1
            continue

        if args.check:
            print(f"DRIFT {name}: {target} out of date")
            stale += 1
            continue

        target_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(want, encoding="utf-8")
        print(f"write {name} -> {target}")

    return 1 if (stale and args.check) else (1 if stale else 0)


if __name__ == "__main__":
    raise SystemExit(main())
