#!/usr/bin/env python3
"""
PPT Master - Codex Stub Sync

Regenerates the Codex discovery stubs under .codex/skills/ from the canonical
Claude skills tree. Each stub carries the canonical SKILL.md's name/description
frontmatter verbatim (so Codex triggering matches Claude Code) plus a fixed
redirect body pointing at the canonical .claude/skills/<name>/ directory. The
.claude tree is the single source of truth; stubs are generated artifacts and
must never be hand-edited. preflight.py runs the --check mode as a hard gate.

Usage:
    python3 scripts/sync_codex_stubs.py [options]

Examples:
    python3 scripts/sync_codex_stubs.py            # regenerate .codex/skills/
    python3 scripts/sync_codex_stubs.py --check    # exit 1 if stubs are stale

Dependencies:
    None (only uses standard library)
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Optional

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from console_encoding import configure_utf8_stdio  # noqa: E402

# scripts/sync_codex_stubs.py: [0]=scripts [1]=ppt-master [2]=skills [3]=.claude [4]=repo
REPO_ROOT = Path(__file__).resolve().parents[4]
SRC = REPO_ROOT / ".claude" / "skills"
DST = REPO_ROOT / ".codex" / "skills"
SYNC_CMD = "python3 .claude/skills/ppt-master/scripts/sync_codex_stubs.py"
FRONTMATTER_KEYS = ("name", "description")

_TOP_KEY_RE = re.compile(r"^([A-Za-z][\w-]*):")

GENERATED_MARKER = f"""# Generated Codex Skill Stubs

This directory is generated by `sync_codex_stubs.py`. Each stub carries the
canonical skill's name/description frontmatter plus a redirect body; the skill
content itself lives only under `.claude/skills/`.

Do not hand-edit files under `.codex/skills`. Edit `.claude/skills`, then run:

    {SYNC_CMD}
"""

# @NAME@ / @CANONICAL@ are replaced at build time. Literal ${SKILL_DIR} must
# survive into the stub, so str.format() is not used here.
STUB_BODY = """
# @NAME@ (Codex discovery stub)

This file is generated by `sync_codex_stubs.py` so Codex discovers the skill.
The authoritative skill lives in this repository at `@CANONICAL@/` — a single
source of truth shared by Claude Code and Codex. Do not hand-edit this stub;
edit the canonical tree, then re-run:

    @SYNC_CMD@

On invocation:

1. Read `@CANONICAL@/SKILL.md` (repo-root relative) in full and execute it
   exactly as a runtime procedure.
2. Resolve paths: treat `${SKILL_DIR}` as `@CANONICAL@`. Bare relative paths
   mentioned inside the skill (`references/...`, `workflows/...`, `scripts/...`,
   `templates/...`) resolve against that directory — never against
   `.codex/skills/`.
3. Run all commands from the repository root. On Windows installs without
   `python3.exe`, rerun the same command with `python`.
"""

# Per-skill extra stub paragraphs — only where Codex-side behavior differs
# from the canonical text.
EXTRA_NOTES = {
    "codex-image": """
4. **Codex adaptation**: the canonical skill was written for Claude Code, which
   shells out through `codex exec` to reach `image_gen`. Inside Codex the
   `image_gen` tool is built in — call it directly with the same
   prompt/size/quality parameters instead of spawning a nested `codex exec`,
   and keep the skill's output-path conventions.
""",
}


def _extract_frontmatter(skill_md: Path) -> list[str]:
    """Return the raw frontmatter lines (between the two --- fences)."""
    lines = skill_md.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{skill_md}: missing frontmatter opening fence")
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return lines[1:i]
    raise ValueError(f"{skill_md}: missing frontmatter closing fence")


def _select_keys(fm_lines: list[str], keys: tuple[str, ...]) -> list[str]:
    """Keep only the given top-level keys, preserving their raw block lines
    (folded/literal scalars keep their continuation lines verbatim)."""
    out: list[str] = []
    keep = False
    for line in fm_lines:
        m = _TOP_KEY_RE.match(line)
        if m:
            keep = m.group(1) in keys
        if keep:
            out.append(line)
    return out


def _render_stub(name: str) -> str:
    canonical = f".claude/skills/{name}"
    fm = _select_keys(_extract_frontmatter(SRC / name / "SKILL.md"),
                      FRONTMATTER_KEYS)
    body = (STUB_BODY
            .replace("@NAME@", name)
            .replace("@CANONICAL@", canonical)
            .replace("@SYNC_CMD@", SYNC_CMD))
    return "---\n" + "\n".join(fm) + "\n---\n" + body + EXTRA_NOTES.get(name, "")


def _skill_names() -> list[str]:
    if not SRC.is_dir():
        raise FileNotFoundError(f"canonical skills tree not found: {SRC}")
    return sorted(p.parent.name for p in SRC.glob("*/SKILL.md"))


def build_stubs(dst: Path) -> None:
    """Regenerate the stub tree at dst (idempotent — wipes and rewrites)."""
    if dst.exists():
        shutil.rmtree(dst)
    for name in _skill_names():
        out = dst / name / "SKILL.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render_stub(name), encoding="utf-8", newline="\n")
    (dst / "_GENERATED.md").write_text(GENERATED_MARKER, encoding="utf-8",
                                       newline="\n")


def _normalized(path: Path) -> bytes:
    """File bytes with CRLF folded to LF, so a git autocrlf checkout does not
    read as drift (content drift is what the gate exists to catch)."""
    return path.read_bytes().replace(b"\r\n", b"\n")


def stale_stub_paths() -> list[str]:
    """Relative paths that differ between .codex/skills and a fresh build.
    Empty list means the stubs are current. Used by --check and preflight."""
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "skills"
        build_stubs(fresh)
        fresh_files = {p.relative_to(fresh) for p in fresh.rglob("*") if p.is_file()}
        dst_files = ({p.relative_to(DST) for p in DST.rglob("*") if p.is_file()}
                     if DST.is_dir() else set())
        stale = []
        for rel in sorted(fresh_files | dst_files, key=str):
            a, b = DST / rel, fresh / rel
            if not a.is_file() or not b.is_file() or _normalized(a) != _normalized(b):
                stale.append(str(rel))
        return stale


def check() -> int:
    stale = stale_stub_paths()
    if stale:
        print(f"[sync_codex_stubs] .codex/skills is STALE ({len(stale)} file(s)):",
              file=sys.stderr)
        for rel in stale:
            print(f"  - {rel}", file=sys.stderr)
        print(f"  Fix: {SYNC_CMD}", file=sys.stderr)
        return 1
    print("[sync_codex_stubs] stubs are current")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Regenerate/verify the .codex/skills Codex discovery stubs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the stubs are stale; do not write")
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    configure_utf8_stdio()
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.check:
        return check()
    build_stubs(DST)
    print(f"[sync_codex_stubs] regenerated {DST.relative_to(REPO_ROOT)} "
          f"from {SRC.relative_to(REPO_ROOT)} ({len(_skill_names())} skill(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
